### ISSUE TITLE
Non-rounded results?

### ISSUE THREAD

**Issue by jweisbeck** [Pephers/Super-Calculator#2]
I'd like the evaluation to not round results. I often need the full fractions when writing CSS. I modified my copy of the package and removed the round call. I'm only asking because this is the only working inline calculator package I know about for SublimeText that reproduces Textmate's evaluate expression shortcut, and I love the feature.

**Comment by Pephers** [comment]
Hi jsweisbeck

Thank you for using my plugin, I'm glad you like it! I have now updated the plugin and added a feature which lets you specify the number of decimals you'd like when the plugin rounds the results. It can be found under Preferences > Package Settings > Super Calculator. The default setting is 2 decimals, but you can change it to say 8 to get more precise results.

/Pephers
