### ISSUE TITLE
First Alt+C doesn't select expression

### ISSUE THREAD

**Issue by amargravity** [Pephers/Super-Calculator#5]
Hi. I have been using sublimetext2 on windows 7 for a few months and Super Calculator was one of my favorite plugins.
Now I have moved on sublimetext3 on Ubuntu 13.04 and when I press Alt+C it doesn't select the expression. If I select the expression and press Alt+C it goes on as expected, replacing the expression with the result.
Is this a bug or am I missing something?

**Comment by Pephers** [comment]
Hi amargravity

Thanks for your bug report. The plugin has just been upgraded with support for Sublime Text 3. Please upgrade and the issue should be fixed.

Best regards,
Chiel
