### ISSUE TITLE
removing zeros

### ISSUE THREAD

**Issue by robsonsobral** [Pephers/Super-Calculator#6]
Hi!

Is it possible to configure the plugin to remove the zeros? For example, to turn `0.30rem` into `.3rem`.

**Comment by Pephers** [comment]
Hi Robson

First of all thanks for using the plugin!

Yes, that can be done by setting the `round_decimals` property to `1` in Preferences > Package Settings > Super Calculator > Settings - User, like so:

```
{
    "round_decimals": 1
}
```

Best regards,
Chiel

**Comment by robsonsobral** [comment]
Hi! Thanks for the quick answer and for the really useful plugin.

Unfortunately, I don't need to round the result, but to remove the zeros to the left before the decimal point and to the right after the decimal point. Even worst, I'm using five decimal points!

```
0.30000rem -> .3rem
0.12500rem -> .125rem
```

I was looking for one setting for this.

**Comment by Pephers** [comment]
Hi Robson

Ah, I see. I'll look at implementing a setting to trim zeros from the result. Thanks for the suggestion!

/Chiel

**Comment by robsonsobral** [comment]
I did! I added the `trim_zeros` setting. It's the first time I write python in my life, but I did. Do you accept a pull request?

**Comment by Pephers** [comment]
Hi Robson. That's so cool. Sure, I do!
