### ISSUE TITLE
ST3 disabled in package control

### ISSUE THREAD

**Issue by Kaligule** [Pephers/Super-Calculator#8]
Since the package control thinks Super-Calculator is for Sublimetext 2 only it cannot be installed with ST3.

https://sublime.wbond.net/packages/Super%20Calculator

**Comment by robsonsobral** [comment]
Is there some issue related to ST3? Why just ST2?

**Comment by robsonsobral** [comment]
Super-Calculator is set as ST2 only on [Package Control](https://github.com/wbond/package_control_channel/blob/master/repository/s.json):

```
"sublime_text": "<3000",
```

But it should be:

```
"sublime_text": "*",
```

For now, you can open the Command Palette, and type `Package Control:Add Repository`. Then enter the URL to this repository: https://github.com/Pephers/Super-Calculator

**Comment by Pephers** [comment]
Hi Robson, thanks for the heads up. I've just submitted a PR to the repository to correct the ST version.

**Comment by Kaligule** [comment]
Link for the lazy ones: https://github.com/wbond/package_control_channel/pull/2954
Hope it gets merged soon ;)
